TrajectoryPlannerROS:
  holonomic_robot: true         # ✅ บอก planner ว่าหุ่นยนต์สามารถเคลื่อนที่แบบ holonomic ได้ (เช่น mecanum หรือ omnidirectional)

  max_vel_x: 0.5                # ความเร็วสูงสุดในแกน X (เดินหน้า) หน่วย: m/s
  min_vel_x: 0.1                # ความเร็วต่ำสุดในแกน X ที่ planner จะพิจารณา (ไม่ควรเป็น 0 เพื่อให้ planner เลือกความเร็วต่ำได้)

  max_vel_y: 0.5                # ความเร็วสูงสุดในแกน Y (เลื่อนข้าง) → ต้องเปิดใช้เฉพาะกับ holonomic robot
  min_vel_y: -0.5               # ความเร็วต่ำสุดในแกน Y (สามารถถอยหลังด้านข้างได้)

  max_vel_theta: 1.0            # ความเร็วหมุนรอบตัวสูงสุด (radians/s)
  min_vel_theta: -1.0           # ความเร็วหมุนรอบตัวต่ำสุด (ค่าลบเพื่อให้หมุนกลับทิศได้)

  acc_lim_x: 2.5                # ความเร่งสูงสุดในแกน X (m/s²)
  acc_lim_y: 2.5                # ความเร่งสูงสุดในแกน Y (m/s²) → ควรมีถ้าใช้ mecanum
  acc_lim_theta: 3.2            # ความเร่งสูงสุดในการหมุน (radians/s²)
