TebLocalPlannerROS:
  # ✅ ตั้งค่าทั่วไป
  odom_topic: odom
  map_frame: odom
  teb_autosize: true
  dt_ref: 0.3
  dt_hysteresis: 0.1
  max_samples: 500

  # ✅ ข้อจำกัดความเร็ว
  max_vel_x: 0.5
  max_vel_y: 0.5
  max_vel_theta: 1.0
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_theta: 3.2

  # ✅ ลักษณะการวาง path
  min_turning_radius: 0.0
  wheelbase: 0.0
  cmd_angle_instead_rotvel: false
  allow_init_with_backwards_motion: true

  # ✅ เป้าหมาย
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.1
  free_goal_vel: false

  # ✅ การเพิ่มประสิทธิภาพ
  weight_kinematics_nh: 1000
  weight_optimaltime: 1
  weight_shortest_path: 0
  weight_obstacle: 50
  weight_viapoint: 1.0

  # ✅ ระบบล้อแบบ Holonomic
  enable_homotopy_class_planning: false
  enable_multithreading: true
  footprint_model:
    type: "polygon"
    vertices: [[-0.15, -0.125], [-0.15, 0.125], [0.15, 0.125], [0.15, -0.125]]
