TebLocalPlannerROS:
  # --- 1. Basic Setup ---
  odom_topic: odom
  map_frame: odom
  teb_autosize: true  # อนุญาตให้ปรับจำนวนจุดในเส้นทางอัตโนมัติ
  dt_ref: 0.3  
  dt_hysteresis: 0.1
  max_samples: 500

  # --- 2. Robot Limits ---
  max_vel_x: 0.5 # ความเร็วเดินหน้าสูงสุด (m/s)
  max_vel_x_backwards: 0.2 # ความเร็วถอยหลังสูงสุด (m/s) // ถอยหลังช้าๆ เพื่อความปลอดภัย
  max_vel_y: 0.5           # ความเร็วสไลด์ข้างสูงสุด (m/s) 
  max_vel_theta: 0.8       # ความเร็วหมุนสูงสุด (rad/s)
  
  acc_lim_x: 0.5           # ความเร่งเดินหน้า (m/s^2)
  acc_lim_y: 0.5           # ความเร่งสไลด์ข้าง (m/s^2)
  acc_lim_theta: 0.5       # ความเร่งการหมุน (rad/s^2)

  # --- 3. Holonomic Settings ---
  min_turning_radius: 0.0 #รัศมีวงเลี้ยวต่ำสุด (0.0 สำหรับ Holonomic)
  cmd_angle_instead_rotvel: false
  
  # --- 4. Goal Tolerance ---
  xy_goal_tolerance: 0.10 # ระยะห่างที่ยอมรับได้เมื่อถึงเป้า (เมตร)
  yaw_goal_tolerance: 0.1 # มุมที่ยอมรับได้เมื่อถึงเป้า (เรเดียน)
  free_goal_vel: false # ยอมให้หุ่นพุ่งผ่านจุดเป้าหมายหรือไม่?

  # --- 5. Obstacle Avoidance---
  min_obstacle_dist: 0.35  # ระยะห่างต่ำสุดจากสิ่งกีดขวาง (เมตร)
  include_costmap_obstacles: true # ใช้ข้อมูลจาก costmap หรือไม่
  costmap_obstacles_behind_robot_dist: 1.0 # ระยะหลังหุ่นที่ยังสนใจสิ่งกีดขวางด้านหลัง (เมตร)
  inflation_dist: 0.45     # ระยะที่เริ่มชะลอความเร็ว

  # --- 6. Optimization Weights ---
  weight_kinematics_nh: 1      #  1 (เพื่อให้สไลด์ข้างได้)
  weight_kinematics_forward_drive: 1 # ความสำคัญของเดินหน้ามากกว่าถอย/สไลด์"
  weight_optimaltime: 1 # น้ำหนัก "ความเร็ว" (Time Optimality)
  weight_obstacle: 50  # น้ำหนัก "กลัวชน"
  weight_viapoint: 1.0 # น้ำหนัก "ผ่านจุดกำหนด"

  # --- 7. Footprint ---
  footprint_model:
    type: "polygon"
    vertices: [[-0.15, -0.125], [-0.15, 0.125], [0.15, 0.125], [0.15, -0.125]]

  # --- 8. Misc ---
  enable_homotopy_class_planning: false # เปิดโหมดคิดหลายเส้นทาง
  enable_multithreading: true # ใช้หลายเธรดเพื่อเร่งการคำนวณ